language: java
jdk:
  - oraclejdk8 
before_install:
  - sudo sh -c 'echo "deb https://packages.atlassian.com/atlassian-sdk-deb stable contrib" >>/etc/apt/sources.list'
  - wget https://packages.atlassian.com/api/gpg/key/public
  - apt-key add public
  - sudo apt-get update
  - sudo apt-get install atlassian-plugin-sdk
install:
  - atlas-mvn -q install -DskipTests=true
script: atlas-unit-test
